name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request] <title>"
labels: [enhancement]
body:
- type: checkboxes
  attributes:
    label: Is there an existing request for this?
    description: Please search to see if a request already exists for the request you encountered.
    options:
    - label: This is not a duplicate
      required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the problem is.
    placeholder: Ex. I'm always frustrated when [...]
  validations:
    required: true
- type: textarea
  attributes:
    label: Feature Request Description
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Feature Request Purpose
    description: A clear and concise description of the purpose of this feature request.
  validations:
    required: true
- type: textarea
  attributes:
    label: Any alternatives?
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional References
    description: |
      Attach internal/external references as well as any related stuffs regarding this feature request
  validations:
    required: false
